export { Icon, type IconProps, type IconSize } from "./icon.js";

/**
 * Jeu d'icones curatees, re-exportees depuis lucide-react (tree-shakeable).
 * Les consommateurs peuvent aussi importer directement depuis "lucide-react".
 */
export {
  Search,
  Settings,
  User,
  Users,
  Plus,
  X,
  Check,
  ChevronDown,
  ChevronRight,
  ChevronLeft,
  ChevronUp,
  Mic,
  Send,
  Trash2,
  Pencil,
  Copy,
  Bell,
  Home,
  LayoutGrid,
  MessageSquare,
  MoreHorizontal,
  Paperclip,
  RefreshCw,
  Square,
  Star,
  StarOff,
  Folder,
  File,
  FileText,
  Terminal,
  Sparkles,
  Sun,
  Moon,
  Monitor,
  Loader2,
  AlertTriangle,
  Info,
  CircleCheck,
  CircleAlert,
  type LucideIcon,
  type LucideProps,
} from "lucide-react";
